In [3]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Pandas

In [5]:
# Install Pandas

In [22]:
import pandas as pd

In [23]:
s = pd.Series([10,20,30])

In [24]:
s

0    10
1    20
2    30
dtype: int64

In [25]:
s = pd.Series([10,20,30], index=['a','b','c'])

In [26]:
s

a    10
b    20
c    30
dtype: int64

In [27]:
student = {
    "name":"Omkar",
    "age":19,
    "marks":70
}

In [28]:
s = pd.Series(student)

In [29]:
s

name     Omkar
age         19
marks       70
dtype: object

In [30]:
print(student)

{'name': 'Omkar', 'age': 19, 'marks': 70}

In [31]:
s = pd.Series(5, index = [0,1,2,3,4])

In [32]:
s

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [33]:
# Attributes

In [34]:
s = pd.Series([10,20,30], index = ['a','b','c'])

In [35]:
s

a    10
b    20
c    30
dtype: int64

In [36]:
s.values

array([10, 20, 30])

In [37]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [38]:
s.dtype

dtype('int64')

In [39]:
s.shape

(3,)

In [40]:
s*2

a    20
b    40
c    60
dtype: int64

In [41]:
s = pd.Series([10,None,20])

In [42]:
s

0    10.0
1     NaN
2    20.0
dtype: float64

In [43]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [44]:
s.dropna()

0    10.0
2    20.0
dtype: float64

In [45]:
s.fillna(5)

0    10.0
1     5.0
2    20.0
dtype: float64

In [46]:
s = pd.Series([1,2,2,3,3,3])

In [47]:
s

0    1
1    2
2    2
3    3
4    3
5    3
dtype: int64

In [48]:
s.value_counts()

3    3
2    2
1    1
Name: count, dtype: int64

In [49]:
s = pd.Series([10,20,30,40], index=['a','b','c','d'])

In [50]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [51]:
s['a']

np.int64(10)

In [52]:
s['b']

np.int64(20)

In [53]:
data ={
    "Name": ["Omkar"],
    "Age": [19],
    "City": [ "Pune"]
}

In [54]:
data

{'Name': ['Omkar'], 'Age': [19], 'City': ['Pune']}

In [82]:
data = {
    "Roll_No":[100,200,300,500],
    "Name":['Omkar','Shrawan','Tanmay','Rahul'],
    "Marks":[99,100,101,626]
}

In [83]:
data

{'Roll_No': [100, 200, 300, 500],
 'Name': ['Omkar', 'Shrawan', 'Tanmay', 'Rahul'],
 'Marks': [99, 100, 101, 626]}

In [84]:
df = pd.DataFrame(data)

In [85]:
df

   Roll_No     Name  Marks
0      100    Omkar     99
1      200  Shrawan    100
2      300   Tanmay    101
3      500    Rahul    626

In [86]:
df.to_csv('Marks_data.csv',index = False)

In [87]:
df = pd.read_csv("Marks_data.csv")

In [88]:
df

   Roll_No     Name  Marks
0      100    Omkar     99
1      200  Shrawan    100
2      300   Tanmay    101
3      500    Rahul    626

In [89]:
df.head()

   Roll_No     Name  Marks
0      100    Omkar     99
1      200  Shrawan    100
2      300   Tanmay    101
3      500    Rahul    626

In [90]:
df.tail()

   Roll_No     Name  Marks
0      100    Omkar     99
1      200  Shrawan    100
2      300   Tanmay    101
3      500    Rahul    626

In [91]:
df.shape

(4, 3)

In [92]:
df.columns

Index(['Roll_No', 'Name', 'Marks'], dtype='object')

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Roll_No  4 non-null      int64
 1   Name     4 non-null      object
 2   Marks    4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [94]:
df.describe()

          Roll_No       Marks
count    4.000000    4.000000
mean   275.000000  231.500000
std    170.782513  263.001267
min    100.000000   99.000000
25%    175.000000   99.750000
50%    250.000000  100.500000
75%    350.000000  232.250000
max    500.000000  626.000000

In [95]:
df.isnull().sum()

Roll_No    0
Name       0
Marks      0
dtype: int64

In [96]:
df =df.drop_duplicates()

In [97]:
df

   Roll_No     Name  Marks
0      100    Omkar     99
1      200  Shrawan    100
2      300   Tanmay    101
3      500    Rahul    626

In [99]:
df['Marks'] = df['Marks'].astype(int)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Roll_No  4 non-null      int64
 1   Name     4 non-null      object
 2   Marks    4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [102]:
df["Name"]

0      Omkar
1    Shrawan
2     Tanmay
3      Rahul
Name: Name, dtype: object

In [109]:
df[["Roll_No","Name"]]

   Roll_No     Name
0      100    Omkar
1      200  Shrawan
2      300   Tanmay
3      500    Rahul

In [111]:
df=df.sort_values(by="Marks",ascending=False)

In [112]:
df

   Roll_No     Name  Marks
3      500    Rahul    626
2      300   Tanmay    101
1      200  Shrawan    100
0      100    Omkar     99